name: Playwright Allure Report Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          # Install missing dependencies for Playwright
          sudo apt-get update
          sudo apt-get install -y \
            libsoup2.4-1 \
            libwoff1 \
            libvpx5 \
            libevent-2.1-7 \
            libopus0 \
            libharfbuzz-icu0 \
            libgstreamer-plugins-base1.0-0 \
            libgstreamer1.0-0 \
            libgstreamer-gl1.0-0 \
            libgstreamer-plugins-good1.0-0 \
            libgstreamer-plugins-bad1.0-0 \
            libgstreamer-plugins-ugly1.0-0 \
            libgstreamer-libav1.0-0 \
            libhyphen0 \
            libmanette-0.2-0 \
            libflite1 \
            libgles2 \
            libx264-152

          # Continue with other setup and testing steps
          npm install
          npx playwright test

      - name: Run Playwright Tests
        run: |
          npx playwright test

      - name: Copy Allure Data
        run: |
          cp -r allure-results/ allure-results-previous

      - name: Generate Allure Report
        run: |
          npm run report

      - name: Push Report to Another Branch
        run: |
          REPORT_BRANCH="report-branch"
          git checkout -b $REPORT_BRANCH
          git add .
          git commit -m "Add Allure report"
          git push origin $REPORT_BRANCH

      - name: Setup GitHub Pages
        run: |
          BRANCH_NAME="report-branch"
          REPO_NAME="$GITHUB_REPOSITORY"
          GITHUB_TOKEN="$GITHUB_TOKEN"
          git checkout $BRANCH_NAME
          git push origin $BRANCH_NAME
