name: Playwright Tests and Report

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests
        run: npx playwright test

      - name: Copy Allure data from previous runs
        run: mkdir allure-results
             cp -r allure-results/. allure-results-previous/

      - name: Create new report
        run: npx allure generate allure-results allure-report

      - name: Push report to another branch
        run: git checkout -b report
             git add allure-report
             git commit -m "Allure report"
             git push origin report

      - name: Add GitHub Pages to branch with report
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createPagesSite({
              owner: context.repo.owner,
              repo: context.repo.repo,
              source: {
                branch: 'report',
                path: '/allure-report',
              },
            })

      - name: Get link for GitHub page
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.getPagesSite({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            .then((response) => {
              console.log(response.data.html_url);
            });

      - name: Add link to GitHub page to description
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              description: `Allure report: [link](${process.env.GITHUB_PAGES_URL})`
            })
