name: Playwright Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copy package.json to runner machine
        run: cp package.json $RUNNER_WORKDIR

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Copy Allure data from previous runs
        run: cp -r --update ./allure-results/history ./allure-results/current

      - name: Create new report
        run: allure generate allure-results/current

      - name: Push report to other branch
        run: git checkout -b allure-report && git add allure-results/report && git commit -m "Allure test report" && git push origin allure-report

      - name: Add GitHub Pages to branch with report
        run: gh-pages -d allure-results/report

      - name: Link to GitHub page in description
        run: |
          github_page_url=$(gh-pages -d allure-results/report -u)
          echo "GitHub page URL: $github_page_url"
          echo "Add this link to the description of the PR."
